insert into ANIMAL (species) values ('Lesser mouse lemur');
insert into ANIMAL (species) values ('Koala');
insert into ANIMAL (species) values ('Western grey kangaroo');
insert into ANIMAL (species) values ('Bear, black');
insert into ANIMAL (species) values ('Anaconda (unidentified)');
insert into ANIMAL (species) values ('Magpie, black-backed');
insert into ANIMAL (species) values ('Baboon, olive');
insert into ANIMAL (species) values ('Spotted deer');
insert into ANIMAL (species) values ('Badger, honey');
insert into ANIMAL (species) values ('Crane, black-crowned');
insert into ANIMAL (species) values ('Lesser mouse lemur');
insert into ANIMAL (species) values ('Marabou stork');
insert into ANIMAL (species) values ('Deer, roe');
insert into ANIMAL (species) values ('Grey phalarope');
insert into ANIMAL (species) values ('Gull, southern black-backed');
insert into ANIMAL (species) values ('Civet, small-toothed palm');
insert into ANIMAL (species) values ('Dragon, komodo');
insert into ANIMAL (species) values ('Badger, eurasian');
insert into ANIMAL (species) values ('Onager');
insert into ANIMAL (species) values ('Toucan, white-throated');
insert into ANIMAL (species) values ('Bear, polar');
insert into ANIMAL (species) values ('Macaque, bonnet');
insert into ANIMAL (species) values ('Fox, pampa gray');
insert into ANIMAL (species) values ('Striped skunk');
insert into ANIMAL (species) values ('Galah');
insert into ANIMAL (species) values ('Knob-nosed goose');
insert into ANIMAL (species) values ('Springbuck');
insert into ANIMAL (species) values ('Egyptian viper');
insert into ANIMAL (species) values ('Iguana, land');
insert into ANIMAL (species) values ('Long-tailed spotted cat');
insert into ANIMAL (species) values ('Caracal');
insert into ANIMAL (species) values ('Tortoise, burmese black mountain');
insert into ANIMAL (species) values ('Tamandua, southern');
insert into ANIMAL (species) values ('Partridge, coqui');
insert into ANIMAL (species) values ('Eagle, tawny');
insert into ANIMAL (species) values ('Ant (unidentified)');
insert into ANIMAL (species) values ('Red and blue macaw');
insert into ANIMAL (species) values ('Antelope, four-horned');
insert into ANIMAL (species) values ('Dog, bush');
insert into ANIMAL (species) values ('Springhare');
insert into ANIMAL (species) values ('Wolf, timber');
insert into ANIMAL (species) values ('Striped dolphin');
insert into ANIMAL (species) values ('Vulture, griffon');
insert into ANIMAL (species) values ('Blackbuck');
insert into ANIMAL (species) values ('Eagle, golden');
insert into ANIMAL (species) values ('Blue and yellow macaw');
insert into ANIMAL (species) values ('Yellow-rumped siskin');
insert into ANIMAL (species) values ('Stork, yellow-billed');
insert into ANIMAL (species) values ('Dove, laughing');
insert into ANIMAL (species) values ('European red squirrel');
insert into ANIMAL (species) values ('Cat, native');
insert into ANIMAL (species) values ('Pine snake (unidentified)');
insert into ANIMAL (species) values ('Hoffman''s sloth');
insert into ANIMAL (species) values ('Booby, blue-faced');
insert into ANIMAL (species) values ('Capuchin, brown');
insert into ANIMAL (species) values ('Gaur');
insert into ANIMAL (species) values ('White-cheeked pintail');
insert into ANIMAL (species) values ('Pelican, brown');
insert into ANIMAL (species) values ('Jackal, asiatic');
insert into ANIMAL (species) values ('Pigeon, wood');
insert into ANIMAL (species) values ('Uinta ground squirrel');
insert into ANIMAL (species) values ('Javan gold-spotted mongoose');
insert into ANIMAL (species) values ('Peccary, white-lipped');
insert into ANIMAL (species) values ('Brown and yellow marshbird');
insert into ANIMAL (species) values ('Otter, brazilian');
insert into ANIMAL (species) values ('Stone sheep');
insert into ANIMAL (species) values ('Defassa waterbuck');
insert into ANIMAL (species) values ('Greater rhea');
insert into ANIMAL (species) values ('Long-tailed jaeger');
insert into ANIMAL (species) values ('Sally lightfoot crab');
insert into ANIMAL (species) values ('Royal tern');
insert into ANIMAL (species) values ('Flamingo, roseat');
insert into ANIMAL (species) values ('American black bear');
insert into ANIMAL (species) values ('Snowy owl');
insert into ANIMAL (species) values ('Badger, european');
insert into ANIMAL (species) values ('Hawk-eagle, crowned');
insert into ANIMAL (species) values ('European stork');
insert into ANIMAL (species) values ('Scarlet macaw');
insert into ANIMAL (species) values ('Coqui partridge');
insert into ANIMAL (species) values ('Stork, painted');
insert into ANIMAL (species) values ('Bear, sloth');
insert into ANIMAL (species) values ('Lechwe, kafue flats');
insert into ANIMAL (species) values ('Brown lemur');
insert into ANIMAL (species) values ('Deer, spotted');
insert into ANIMAL (species) values ('Lizard, mexican beaded');
insert into ANIMAL (species) values ('Whale, southern right');
insert into ANIMAL (species) values ('Blue peacock');
insert into ANIMAL (species) values ('Puffin, horned');
insert into ANIMAL (species) values ('Oryx, fringe-eared');
insert into ANIMAL (species) values ('Macaw, blue and yellow');
insert into ANIMAL (species) values ('Water legaan');
insert into ANIMAL (species) values ('Currasow (unidentified)');
insert into ANIMAL (species) values ('Red-billed toucan');
insert into ANIMAL (species) values ('White-eye, cape');
insert into ANIMAL (species) values ('Pademelon, red-legged');
insert into ANIMAL (species) values ('Shrike, crimson-breasted');
insert into ANIMAL (species) values ('Common turkey');
insert into ANIMAL (species) values ('Asiatic jackal');
insert into ANIMAL (species) values ('Malachite kingfisher');
