CREATE TABLE FLORA_GROW(
   F_species VARCHAR(16) NOT NULL PRIMARY KEY
  ,F_park_id INTEGER  NOT NULL
);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Pink Tickseed',100);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Pink Tickseed',101);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Pink Tickseed',102);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Pink Tickseed',103);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Pink Tickseed',104);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Pink Tickseed',105);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Pink Tickseed',106);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Pink Tickseed',107);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Pink Tickseed',108);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Pink Tickseed',109);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Pink Tickseed',110);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Pink Tickseed',111);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Pink Tickseed',112);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Pink Tickseed',113);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Pink Tickseed',114);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Pink Tickseed',115);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Pink Tickseed',116);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Pink Tickseed',117);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Pink Tickseed',118);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Earleaf Acacia',119);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Earleaf Acacia',120);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Earleaf Acacia',121);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Earleaf Acacia',122);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Earleaf Acacia',123);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Earleaf Acacia',124);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Earleaf Acacia',125);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Earleaf Acacia',126);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Earleaf Acacia',127);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Earleaf Acacia',128);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Earleaf Acacia',129);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Earleaf Acacia',130);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Earleaf Acacia',131);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Earleaf Acacia',132);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Earleaf Acacia',133);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Earleaf Acacia',134);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Earleaf Acacia',135);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Earleaf Acacia',136);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Earleaf Acacia',137);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Earleaf Acacia',138);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Earleaf Acacia',139);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Earleaf Acacia',140);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Earleaf Acacia',141);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Cynodontium Moss',142);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Cynodontium Moss',143);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Cynodontium Moss',144);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Cynodontium Moss',145);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Cynodontium Moss',146);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Cynodontium Moss',147);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Cynodontium Moss',148);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Cynodontium Moss',149);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Cynodontium Moss',150);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Cynodontium Moss',151);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Cynodontium Moss',152);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Cynodontium Moss',153);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Cynodontium Moss',154);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Cynodontium Moss',155);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Cynodontium Moss',156);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Cynodontium Moss',157);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Cynodontium Moss',158);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Cynodontium Moss',159);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Cynodontium Moss',160);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Cynodontium Moss',161);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Sanchezia',162);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Sanchezia',163);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Sanchezia',164);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Sanchezia',165);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Sanchezia',166);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Sanchezia',167);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Sanchezia',168);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Sanchezia',169);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Sanchezia',170);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Sanchezia',171);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Sanchezia',172);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Sanchezia',173);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Sanchezia',174);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Sanchezia',175);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Sanchezia',176);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Sanchezia',177);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Sanchezia',178);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Sanchezia',179);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Sanchezia',180);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Sanchezia',181);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Wart Lichen',182);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Wart Lichen',183);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Wart Lichen',184);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Wart Lichen',185);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Wart Lichen',186);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Wart Lichen',187);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Wart Lichen',188);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Wart Lichen',189);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Wart Lichen',190);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Wart Lichen',191);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Wart Lichen',192);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Wart Lichen',193);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Wart Lichen',194);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Wart Lichen',195);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Wart Lichen',196);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Wart Lichen',197);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Wart Lichen',198);
INSERT INTO FLORA_GROW(F_species,F_park_id) VALUES ('Wart Lichen',199);
