insert into MOCK_DATA (office_id, office_name, address) values (10066, 'Legal', '766 Scott Circle');
insert into MOCK_DATA (office_id, office_name, address) values (10071, 'Research and Development', '10469 Namekagon Trail');
insert into MOCK_DATA (office_id, office_name, address) values (10042, 'Training', '10131 Maple Alley');
insert into MOCK_DATA (office_id, office_name, address) values (10044, 'Marketing', '8 Bobwhite Road');
insert into MOCK_DATA (office_id, office_name, address) values (10058, 'Business Development', '66979 Warrior Plaza');
insert into MOCK_DATA (office_id, office_name, address) values (10031, 'Training', '6104 Forest Run Alley');
insert into MOCK_DATA (office_id, office_name, address) values (10071, 'Services', '5544 Sachtjen Court');
insert into MOCK_DATA (office_id, office_name, address) values (10091, 'Accounting', '79 Iowa Center');
insert into MOCK_DATA (office_id, office_name, address) values (10085, 'Accounting', '40722 Crowley Point');
insert into MOCK_DATA (office_id, office_name, address) values (10041, 'Sales', '4 Brickson Park Way');
insert into MOCK_DATA (office_id, office_name, address) values (10085, 'Support', '9 Westport Park');
insert into MOCK_DATA (office_id, office_name, address) values (10008, 'Accounting', '11 Sommers Drive');
insert into MOCK_DATA (office_id, office_name, address) values (10013, 'Product Management', '1 Crowley Lane');
insert into MOCK_DATA (office_id, office_name, address) values (10029, 'Business Development', '3898 Moose Junction');
insert into MOCK_DATA (office_id, office_name, address) values (10076, 'Human Resources', '0745 Lukken Alley');
insert into MOCK_DATA (office_id, office_name, address) values (10062, 'Human Resources', '38653 Raven Place');
insert into MOCK_DATA (office_id, office_name, address) values (10017, 'Human Resources', '824 Waxwing Center');
insert into MOCK_DATA (office_id, office_name, address) values (10011, 'Engineering', '5 Bunting Park');
insert into MOCK_DATA (office_id, office_name, address) values (10028, 'Research and Development', '60961 American Ash Circle');
insert into MOCK_DATA (office_id, office_name, address) values (10056, 'Legal', '40 West Terrace');
insert into MOCK_DATA (office_id, office_name, address) values (10061, 'Marketing', '28 Parkside Crossing');
insert into MOCK_DATA (office_id, office_name, address) values (10036, 'Business Development', '325 Portage Trail');
insert into MOCK_DATA (office_id, office_name, address) values (10040, 'Training', '7 Caliangt Point');
insert into MOCK_DATA (office_id, office_name, address) values (10007, 'Legal', '3 Chinook Avenue');
insert into MOCK_DATA (office_id, office_name, address) values (10071, 'Sales', '0 Stoughton Place');
insert into MOCK_DATA (office_id, office_name, address) values (10027, 'Engineering', '05 Northridge Junction');
insert into MOCK_DATA (office_id, office_name, address) values (10009, 'Training', '4 Stoughton Drive');
insert into MOCK_DATA (office_id, office_name, address) values (10060, 'Human Resources', '4 Spenser Junction');
insert into MOCK_DATA (office_id, office_name, address) values (10013, 'Human Resources', '18540 Annamark Pass');
insert into MOCK_DATA (office_id, office_name, address) values (10082, 'Engineering', '9 Hoepker Plaza');
insert into MOCK_DATA (office_id, office_name, address) values (10048, 'Research and Development', '5 Butternut Center');
insert into MOCK_DATA (office_id, office_name, address) values (10079, 'Legal', '8 Declaration Crossing');
insert into MOCK_DATA (office_id, office_name, address) values (10055, 'Accounting', '5 North Trail');
insert into MOCK_DATA (office_id, office_name, address) values (10057, 'Business Development', '000 Montana Court');
insert into MOCK_DATA (office_id, office_name, address) values (10061, 'Product Management', '45343 Jenna Avenue');
insert into MOCK_DATA (office_id, office_name, address) values (10070, 'Accounting', '8 Oxford Point');
insert into MOCK_DATA (office_id, office_name, address) values (10041, 'Accounting', '31 Blaine Junction');
insert into MOCK_DATA (office_id, office_name, address) values (10051, 'Training', '4145 Calypso Parkway');
insert into MOCK_DATA (office_id, office_name, address) values (10034, 'Support', '97463 American Ash Parkway');
insert into MOCK_DATA (office_id, office_name, address) values (10040, 'Legal', '43 Cardinal Pass');
insert into MOCK_DATA (office_id, office_name, address) values (10026, 'Product Management', '1796 3rd Drive');
insert into MOCK_DATA (office_id, office_name, address) values (10066, 'Training', '86 Kinsman Plaza');
insert into MOCK_DATA (office_id, office_name, address) values (10061, 'Training', '4481 Rutledge Hill');
insert into MOCK_DATA (office_id, office_name, address) values (10093, 'Accounting', '3787 Hauk Street');
insert into MOCK_DATA (office_id, office_name, address) values (10017, 'Services', '6 Golf View Way');
insert into MOCK_DATA (office_id, office_name, address) values (10015, 'Legal', '38802 Lukken Trail');
insert into MOCK_DATA (office_id, office_name, address) values (10085, 'Human Resources', '693 Muir Point');
insert into MOCK_DATA (office_id, office_name, address) values (10000, 'Engineering', '79435 Shopko Plaza');
insert into MOCK_DATA (office_id, office_name, address) values (10083, 'Training', '2 Dahle Way');
insert into MOCK_DATA (office_id, office_name, address) values (10084, 'Services', '194 Del Mar Alley');
insert into MOCK_DATA (office_id, office_name, address) values (10066, 'Services', '411 Londonderry Parkway');
insert into MOCK_DATA (office_id, office_name, address) values (10029, 'Business Development', '3 Division Point');
insert into MOCK_DATA (office_id, office_name, address) values (10093, 'Business Development', '9491 Michigan Parkway');
insert into MOCK_DATA (office_id, office_name, address) values (10083, 'Support', '65540 Forster Hill');
insert into MOCK_DATA (office_id, office_name, address) values (10095, 'Support', '2 Burrows Avenue');
insert into MOCK_DATA (office_id, office_name, address) values (10082, 'Product Management', '1 West Avenue');
insert into MOCK_DATA (office_id, office_name, address) values (10047, 'Services', '3943 Golf Plaza');
insert into MOCK_DATA (office_id, office_name, address) values (10086, 'Engineering', '14 Village Green Alley');
insert into MOCK_DATA (office_id, office_name, address) values (10080, 'Product Management', '37 South Hill');
insert into MOCK_DATA (office_id, office_name, address) values (10020, 'Business Development', '1605 Carey Crossing');
insert into MOCK_DATA (office_id, office_name, address) values (10041, 'Human Resources', '7146 Redwing Road');
insert into MOCK_DATA (office_id, office_name, address) values (10046, 'Product Management', '28 Sloan Point');
insert into MOCK_DATA (office_id, office_name, address) values (10031, 'Training', '214 Superior Hill');
insert into MOCK_DATA (office_id, office_name, address) values (10038, 'Sales', '02 Fremont Street');
insert into MOCK_DATA (office_id, office_name, address) values (10033, 'Marketing', '534 Summer Ridge Place');
insert into MOCK_DATA (office_id, office_name, address) values (10100, 'Accounting', '062 Pine View Hill');
insert into MOCK_DATA (office_id, office_name, address) values (10044, 'Sales', '560 Monument Lane');
insert into MOCK_DATA (office_id, office_name, address) values (10019, 'Product Management', '6240 Ridgeview Parkway');
insert into MOCK_DATA (office_id, office_name, address) values (10028, 'Marketing', '8 Dawn Hill');
insert into MOCK_DATA (office_id, office_name, address) values (10072, 'Research and Development', '4069 Maryland Park');
insert into MOCK_DATA (office_id, office_name, address) values (10026, 'Human Resources', '2 Kim Street');
insert into MOCK_DATA (office_id, office_name, address) values (10044, 'Sales', '6403 Packers Street');
insert into MOCK_DATA (office_id, office_name, address) values (10000, 'Sales', '37 Mendota Circle');
insert into MOCK_DATA (office_id, office_name, address) values (10068, 'Sales', '3006 Blaine Parkway');
insert into MOCK_DATA (office_id, office_name, address) values (10006, 'Services', '0 Bellgrove Avenue');
insert into MOCK_DATA (office_id, office_name, address) values (10072, 'Training', '146 Melrose Point');
insert into MOCK_DATA (office_id, office_name, address) values (10046, 'Training', '9709 Pine View Court');
insert into MOCK_DATA (office_id, office_name, address) values (10037, 'Sales', '7476 Carpenter Crossing');
insert into MOCK_DATA (office_id, office_name, address) values (10060, 'Accounting', '095 Rigney Road');
insert into MOCK_DATA (office_id, office_name, address) values (10022, 'Training', '87 Golf Course Hill');
insert into MOCK_DATA (office_id, office_name, address) values (10037, 'Support', '2 Summit Street');
insert into MOCK_DATA (office_id, office_name, address) values (10030, 'Sales', '19145 Fairfield Avenue');
insert into MOCK_DATA (office_id, office_name, address) values (10056, 'Services', '95773 Erie Road');
insert into MOCK_DATA (office_id, office_name, address) values (10031, 'Legal', '478 Carberry Junction');
insert into MOCK_DATA (office_id, office_name, address) values (10019, 'Training', '4 Nova Court');
insert into MOCK_DATA (office_id, office_name, address) values (10053, 'Research and Development', '6039 Carberry Hill');
insert into MOCK_DATA (office_id, office_name, address) values (10045, 'Services', '713 Talmadge Trail');
insert into MOCK_DATA (office_id, office_name, address) values (10045, 'Engineering', '75 Hayes Park');
insert into MOCK_DATA (office_id, office_name, address) values (10051, 'Accounting', '417 Caliangt Parkway');
insert into MOCK_DATA (office_id, office_name, address) values (10066, 'Accounting', '54 Troy Circle');
insert into MOCK_DATA (office_id, office_name, address) values (10087, 'Support', '6288 Dennis Road');
insert into MOCK_DATA (office_id, office_name, address) values (10030, 'Research and Development', '7630 Cascade Center');
insert into MOCK_DATA (office_id, office_name, address) values (10078, 'Human Resources', '1 Bartillon Lane');
insert into MOCK_DATA (office_id, office_name, address) values (10068, 'Accounting', '88949 Mockingbird Park');
insert into MOCK_DATA (office_id, office_name, address) values (10066, 'Marketing', '0733 Vahlen Junction');
insert into MOCK_DATA (office_id, office_name, address) values (10064, 'Engineering', '9433 Daystar Avenue');
insert into MOCK_DATA (office_id, office_name, address) values (10036, 'Human Resources', '18 Cardinal Crossing');
insert into MOCK_DATA (office_id, office_name, address) values (10074, 'Sales', '85 Oriole Center');
insert into MOCK_DATA (office_id, office_name, address) values (10053, 'Engineering', '0674 Lakewood Pass');
insert into MOCK_DATA (office_id, office_name, address) values (10038, 'Engineering', '4261 Nova Road');
