insert into OFFICE (office_id, office_name, address) values (10001, 'Sales', '15920 Marcy Place');
insert into OFFICE (office_id, office_name, address) values (10002, 'Product Management', '7797 Division Court');
insert into OFFICE (office_id, office_name, address) values (10003, 'Accounting', '01272 Nevada Crossing');
insert into OFFICE (office_id, office_name, address) values (10004, 'Training', '3 Northland Way');
insert into OFFICE (office_id, office_name, address) values (10033, 'Support', '7682 Bashford Avenue');
insert into OFFICE (office_id, office_name, address) values (10015, 'Accounting', '18 Sage Avenue');
insert into OFFICE (office_id, office_name, address) values (10028, 'Research and Development', '39092 Pennsylvania Way');
insert into OFFICE (office_id, office_name, address) values (10080, 'Accounting', '59 Mitchell Parkway');
insert into OFFICE (office_id, office_name, address) values (10083, 'Training', '8 Village Crossing');
insert into OFFICE (office_id, office_name, address) values (10099, 'Research and Development', '7 Bowman Alley');
insert into OFFICE (office_id, office_name, address) values (10030, 'Accounting', '78592 Vermont Place');
insert into OFFICE (office_id, office_name, address) values (10045, 'Accounting', '60716 Nevada Avenue');
insert into OFFICE (office_id, office_name, address) values (10038, 'Training', '100 Erie Hill');
insert into OFFICE (office_id, office_name, address) values (10068, 'Accounting', '1 Talisman Alley');
insert into OFFICE (office_id, office_name, address) values (10062, 'Legal', '71848 Alpine Junction');
insert into OFFICE (office_id, office_name, address) values (10083, 'Legal', '74 Northwestern Place');
insert into OFFICE (office_id, office_name, address) values (10000, 'Services', '83 Dexter Court');
insert into OFFICE (office_id, office_name, address) values (10041, 'Training', '0 2nd Terrace');
insert into OFFICE (office_id, office_name, address) values (10091, 'Research and Development', '387 Cardinal Alley');
insert into OFFICE (office_id, office_name, address) values (10016, 'Business Development', '095 Arkansas Crossing');
insert into OFFICE (office_id, office_name, address) values (10002, 'Sales', '82659 Sunnyside Pass');
insert into OFFICE (office_id, office_name, address) values (10014, 'Support', '0238 Fallview Avenue');
insert into OFFICE (office_id, office_name, address) values (10075, 'Engineering', '761 Oriole Court');
insert into OFFICE (office_id, office_name, address) values (10054, 'Support', '9 Myrtle Plaza');
insert into OFFICE (office_id, office_name, address) values (10061, 'Marketing', '114 Marquette Lane');
insert into OFFICE (office_id, office_name, address) values (10094, 'Legal', '2445 Artisan Crossing');
insert into OFFICE (office_id, office_name, address) values (10006, 'Training', '57092 Lakewood Parkway');
insert into OFFICE (office_id, office_name, address) values (10096, 'Services', '1 Crownhardt Trail');
insert into OFFICE (office_id, office_name, address) values (10088, 'Sales', '5578 Nancy Point');
insert into OFFICE (office_id, office_name, address) values (10009, 'Services', '2 Canary Place');
insert into OFFICE (office_id, office_name, address) values (10053, 'Services', '221 Twin Pines Hill');
insert into OFFICE (office_id, office_name, address) values (10095, 'Engineering', '222 Melody Circle');
insert into OFFICE (office_id, office_name, address) values (10047, 'Sales', '660 Victoria Point');
insert into OFFICE (office_id, office_name, address) values (10041, 'Accounting', '9 Emmet Junction');
insert into OFFICE (office_id, office_name, address) values (10068, 'Marketing', '58 Talisman Street');
insert into OFFICE (office_id, office_name, address) values (10089, 'Sales', '795 Del Sol Road');
insert into OFFICE (office_id, office_name, address) values (10055, 'Training', '2597 Sheridan Way');
insert into OFFICE (office_id, office_name, address) values (10004, 'Research and Development', '713 Evergreen Road');
insert into OFFICE (office_id, office_name, address) values (10039, 'Training', '201 Vermont Avenue');
insert into OFFICE (office_id, office_name, address) values (10041, 'Sales', '81565 Steensland Trail');
insert into OFFICE (office_id, office_name, address) values (10011, 'Business Development', '49 Larry Point');
insert into OFFICE (office_id, office_name, address) values (10042, 'Business Development', '9 6th Avenue');
insert into OFFICE (office_id, office_name, address) values (10037, 'Human Resources', '39608 Grasskamp Avenue');
insert into OFFICE (office_id, office_name, address) values (10061, 'Marketing', '27804 North Terrace');
insert into OFFICE (office_id, office_name, address) values (10021, 'Research and Development', '43676 Stang Place');
insert into OFFICE (office_id, office_name, address) values (10043, 'Human Resources', '1 Anzinger Lane');
insert into OFFICE (office_id, office_name, address) values (10046, 'Engineering', '46045 Chinook Junction');
insert into OFFICE (office_id, office_name, address) values (10095, 'Training', '0447 Pine View Hill');
insert into OFFICE (office_id, office_name, address) values (10075, 'Product Management', '4762 6th Way');
insert into OFFICE (office_id, office_name, address) values (10087, 'Product Management', '549 Laurel Way');
insert into OFFICE (office_id, office_name, address) values (10007, 'Research and Development', '63 Moulton Circle');
insert into OFFICE (office_id, office_name, address) values (10035, 'Support', '9 Kenwood Hill');
insert into OFFICE (office_id, office_name, address) values (10057, 'Marketing', '071 Tomscot Court');
insert into OFFICE (office_id, office_name, address) values (10046, 'Sales', '8 Heffernan Parkway');
insert into OFFICE (office_id, office_name, address) values (10088, 'Product Management', '2 Graedel Point');
insert into OFFICE (office_id, office_name, address) values (10060, 'Engineering', '4 Northwestern Circle');
insert into OFFICE (office_id, office_name, address) values (10060, 'Marketing', '69057 Vermont Street');
insert into OFFICE (office_id, office_name, address) values (10064, 'Accounting', '582 Northfield Circle');
insert into OFFICE (office_id, office_name, address) values (10036, 'Research and Development', '93429 Armistice Junction');
insert into OFFICE (office_id, office_name, address) values (10061, 'Services', '2 Ridgeway Terrace');
insert into OFFICE (office_id, office_name, address) values (10006, 'Services', '1 Forster Trail');
insert into OFFICE (office_id, office_name, address) values (10061, 'Services', '7 Nancy Trail');
insert into OFFICE (office_id, office_name, address) values (10076, 'Legal', '5 Onsgard Alley');
insert into OFFICE (office_id, office_name, address) values (10071, 'Support', '44241 Huxley Drive');
insert into OFFICE (office_id, office_name, address) values (10100, 'Sales', '9 Ohio Terrace');
insert into OFFICE (office_id, office_name, address) values (10034, 'Accounting', '39 Donald Park');
insert into OFFICE (office_id, office_name, address) values (10005, 'Business Development', '37592 Cherokee Trail');
insert into OFFICE (office_id, office_name, address) values (10038, 'Marketing', '6949 Rowland Court');
insert into OFFICE (office_id, office_name, address) values (10054, 'Accounting', '10 Algoma Point');
insert into OFFICE (office_id, office_name, address) values (10017, 'Support', '47 Portage Trail');
insert into OFFICE (office_id, office_name, address) values (10027, 'Accounting', '441 Homewood Court');
insert into OFFICE (office_id, office_name, address) values (10027, 'Marketing', '350 Briar Crest Way');
insert into OFFICE (office_id, office_name, address) values (10017, 'Research and Development', '0 Crownhardt Pass');
insert into OFFICE (office_id, office_name, address) values (10003, 'Accounting', '5 Raven Center');
insert into OFFICE (office_id, office_name, address) values (10085, 'Marketing', '05 Annamark Place');
insert into OFFICE (office_id, office_name, address) values (10016, 'Human Resources', '86 Milwaukee Court');
insert into OFFICE (office_id, office_name, address) values (10094, 'Legal', '1434 Prairieview Junction');
insert into OFFICE (office_id, office_name, address) values (10017, 'Support', '7 Springs Court');
insert into OFFICE (office_id, office_name, address) values (10022, 'Engineering', '97 Milwaukee Court');
insert into OFFICE (office_id, office_name, address) values (10071, 'Services', '173 Forest Pass');
insert into OFFICE (office_id, office_name, address) values (10045, 'Legal', '056 Melrose Point');
insert into OFFICE (office_id, office_name, address) values (10082, 'Accounting', '8 Thompson Street');
insert into OFFICE (office_id, office_name, address) values (10059, 'Engineering', '8237 Esker Avenue');
insert into OFFICE (office_id, office_name, address) values (10071, 'Support', '6 Shoshone Park');
insert into OFFICE (office_id, office_name, address) values (10044, 'Product Management', '79531 Grim Plaza');
insert into OFFICE (office_id, office_name, address) values (10004, 'Marketing', '7 Memorial Terrace');
insert into OFFICE (office_id, office_name, address) values (10098, 'Product Management', '11 Jay Place');
insert into OFFICE (office_id, office_name, address) values (10001, 'Product Management', '6 Esker Circle');
insert into OFFICE (office_id, office_name, address) values (10080, 'Engineering', '5 Oakridge Place');
insert into OFFICE (office_id, office_name, address) values (10034, 'Human Resources', '0 High Crossing Circle');
insert into OFFICE (office_id, office_name, address) values (10079, 'Accounting', '9 Brentwood Plaza');
insert into OFFICE (office_id, office_name, address) values (10043, 'Research and Development', '98 Butternut Trail');
insert into OFFICE (office_id, office_name, address) values (10015, 'Support', '1301 Pawling Parkway');
insert into OFFICE (office_id, office_name, address) values (10039, 'Services', '69551 Macpherson Drive');
insert into OFFICE (office_id, office_name, address) values (10069, 'Engineering', '0 Del Mar Circle');
insert into OFFICE (office_id, office_name, address) values (10079, 'Human Resources', '42100 Autumn Leaf Pass');
insert into OFFICE (office_id, office_name, address) values (10057, 'Research and Development', '1 Northridge Terrace');
insert into OFFICE (office_id, office_name, address) values (10071, 'Services', '7921 Sycamore Street');
insert into OFFICE (office_id, office_name, address) values (10097, 'Sales', '881 Ludington Place');
insert into OFFICE (office_id, office_name, address) values (10014, 'Services', '706 Corry Lane');
