insert into FLORA (species) values ('Chaparral Bird''s-foot Trefoil');
insert into FLORA (species) values ('Degel''s Wart Lichen');
insert into FLORA (species) values ('San Francisco Campion');
insert into FLORA (species) values ('Fireweed');
insert into FLORA (species) values ('Stellate Orthotrichum Moss');
insert into FLORA (species) values ('Roundflower Catclaw');
insert into FLORA (species) values ('Needle Lichen');
insert into FLORA (species) values ('Histiopteris');
insert into FLORA (species) values ('Small''s Jointweed');
insert into FLORA (species) values ('Pink Tickseed');
insert into FLORA (species) values ('Cypressvine');
insert into FLORA (species) values ('Urceolate Conotrema Lichen');
insert into FLORA (species) values ('Low Rattlebox');
insert into FLORA (species) values ('Nightflowering Silene');
insert into FLORA (species) values ('Locoto');
insert into FLORA (species) values ('Arizona Madrone');
insert into FLORA (species) values ('Opium Poppy');
insert into FLORA (species) values ('Bailey''s Sedge');
insert into FLORA (species) values ('Kern Mallow');
insert into FLORA (species) values ('Arctic Teloschistes Lichen');
insert into FLORA (species) values ('Bellemerea Lichen');
insert into FLORA (species) values ('Rocky Mountain Spikemoss');
insert into FLORA (species) values ('Kellogg''s Tarweed');
insert into FLORA (species) values ('Waxyfruit Hawthorn');
insert into FLORA (species) values ('Helodium Moss');
insert into FLORA (species) values ('San Francisco Campion');
insert into FLORA (species) values ('Earleaf Acacia');
insert into FLORA (species) values ('Bentspike Fountaingrass');
insert into FLORA (species) values ('Hummingbird Sage');
insert into FLORA (species) values ('Veiny Pepperweed');
insert into FLORA (species) values ('Sakhalin Corktree');
insert into FLORA (species) values ('Wallowa Needlegrass');
insert into FLORA (species) values ('Ogeechee Tupelo');
insert into FLORA (species) values ('Parasitic Lady''s Tresses');
insert into FLORA (species) values ('Hygrohypnum Moss');
insert into FLORA (species) values ('Himalaya Fishscale Lichen');
insert into FLORA (species) values ('Idaho Licorice-root');
insert into FLORA (species) values ('Nuttall''s Rockcress');
insert into FLORA (species) values ('Oregon Gumweed');
insert into FLORA (species) values ('Hillside Vervain');
insert into FLORA (species) values ('Seaside Coccotrema Lichen');
insert into FLORA (species) values ('Sporopodium Lichen');
insert into FLORA (species) values ('Heermann''s Buckwheat');
insert into FLORA (species) values ('Low Philonotis Moss');
insert into FLORA (species) values ('Cynodontium Moss');
insert into FLORA (species) values ('Flatstem Spikerush');
insert into FLORA (species) values ('Wholeleaf Indian Paintbrush');
insert into FLORA (species) values ('Texas Willkommia');
insert into FLORA (species) values ('Spotted Beebalm');
insert into FLORA (species) values ('Narrowleaf Wildparsley');
insert into FLORA (species) values ('Virginia Strawberry');
insert into FLORA (species) values ('Rio Grande Nailwort');
insert into FLORA (species) values ('Hairy Beggarticks');
insert into FLORA (species) values ('Purple Fleabane');
insert into FLORA (species) values ('Hybrid Violet');
insert into FLORA (species) values ('Creeping Alkaligrass');
insert into FLORA (species) values ('Dotted Bristle Fern');
insert into FLORA (species) values ('Wild Indigo');
insert into FLORA (species) values ('Lempholemma Lichen');
insert into FLORA (species) values ('Hawthorn');
insert into FLORA (species) values ('Wavy Scaly Cloakfern');
insert into FLORA (species) values ('Softleaf Blackberry');
insert into FLORA (species) values ('Gregg''s Sensitive Pea');
insert into FLORA (species) values ('Curlytop Gumweed');
insert into FLORA (species) values ('Mountain Phacelia');
insert into FLORA (species) values ('Japanese Tree Lilac');
insert into FLORA (species) values ('Gordon''s Bladderpod');
insert into FLORA (species) values ('Dore''s Needlegrass');
insert into FLORA (species) values ('Ajo Rockdaisy');
insert into FLORA (species) values ('Red Fescue');
insert into FLORA (species) values ('Cushion Buckwheat');
insert into FLORA (species) values ('Plateau Spiderwort');
insert into FLORA (species) values ('Podranea');
insert into FLORA (species) values ('Stinging Nettle');
insert into FLORA (species) values ('Eggleston''s Milkvetch');
insert into FLORA (species) values ('Channel Millet');
insert into FLORA (species) values ('Hybrid Cloakfern');
insert into FLORA (species) values ('Thickstem Aster');
insert into FLORA (species) values ('Bursting-heart');
insert into FLORA (species) values ('Plains Evening Primrose');
insert into FLORA (species) values ('Physcomitrium Moss');
insert into FLORA (species) values ('Jersey Knapweed');
insert into FLORA (species) values ('Panamint Springparsley');
insert into FLORA (species) values ('Waihanau Lobelia');
insert into FLORA (species) values ('Rinodina Lichen');
insert into FLORA (species) values ('Obtuseleaf Fissidens Moss');
insert into FLORA (species) values ('Rock''s Nehe');
insert into FLORA (species) values ('Sanchezia');
insert into FLORA (species) values ('Sorghum');
insert into FLORA (species) values ('White Garlic');
insert into FLORA (species) values ('Hairyflower Buckwheat');
insert into FLORA (species) values ('Thelenella Lichen');
insert into FLORA (species) values ('Manystem Liveforever');
insert into FLORA (species) values ('Scarletfruit Passionflower');
insert into FLORA (species) values ('Duke Hawthorn');
insert into FLORA (species) values ('Indian Bark');
insert into FLORA (species) values ('Hamatocactus');
insert into FLORA (species) values ('Wart Lichen');
insert into FLORA (species) values ('Heartleaf Iceplant');
insert into FLORA (species) values ('Woodland Bluegrass');
