INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob ,Visitor_num,Annual_pass_holder) VALUES (101,'Marianna','McAllen','Female','2000-05-31',1,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob ,Visitor_num,Annual_pass_holder) VALUES (101,'Eolande','Boulde','Male','2001-01-25',2,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob ,Visitor_num,Annual_pass_holder) VALUES (101,'Natty','Dono','Non-binary','2000-07-24',3,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob ,Visitor_num,Annual_pass_holder) VALUES (101,'Yevette','Sleeny','Male','2000-07-17',4,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob ,Visitor_num,Annual_pass_holder) VALUES (101,'Em','Brixey','Female','2001-02-10',5,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob ,Visitor_num,Annual_pass_holder) VALUES (101,'Gan','Fosbraey','Female','2000-08-01',6,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob ,Visitor_num,Annual_pass_holder) VALUES (101,'Shell','Lynskey','Female','2000-10-10',7,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob ,Visitor_num,Annual_pass_holder) VALUES (101,'Estrellita','Landes','Female','2001-03-16',8,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob ,Visitor_num,Annual_pass_holder) VALUES (101,'Yorgo','Farnham','Male','2000-10-16',9,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob ,Visitor_num,Annual_pass_holder) VALUES (101,'Wilbert','Niccols','Non-binary','2000-10-18',10,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob ,Visitor_num,Annual_pass_holder) VALUES (101,'Gretal','Aartsen','Male','2001-02-19',11,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob ,Visitor_num,Annual_pass_holder) VALUES (101,'Kellsie','Grason','Female','2001-01-10',12,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob ,Visitor_num,Annual_pass_holder) VALUES (101,'Simona','Courcey','Male','2000-06-20',13,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob ,Visitor_num,Annual_pass_holder) VALUES (101,'Myrna','Turmel','Male','2000-09-26',14,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob ,Visitor_num,Annual_pass_holder) VALUES (101,'Lindy','Tankard','Non-binary','2001-04-27',15,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob ,Visitor_num,Annual_pass_holder) VALUES (102,'Patin','Tuffey','Female','2000-07-27',16,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob ,Visitor_num,Annual_pass_holder) VALUES (102,'Sally','McLese','Non-binary','2000-12-28',17,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob ,Visitor_num,Annual_pass_holder) VALUES (102,'Mattias','Blance','Male','2000-10-06',18,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob ,Visitor_num,Annual_pass_holder) VALUES (102,'Welch','Line','Female','2001-03-20',19,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Jonas','Caldroni','Male','2000-08-20',20,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Coletta','Eccleston','Female','2001-01-14',21,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Ezri','Crinage','Male','2000-08-18',22,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Kylen','Boness','Female','2000-09-30',23,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Adlai','Donnell','Non-binary','2001-05-23',24,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Daphna','Autrie','Female','2001-04-26',25,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Felecia','Rundall','Male','2001-04-28',26,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Erie','Egdell','Non-binary','2001-01-09',27,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Aloise','Jancik','Female','2000-08-08',28,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Connor','Honnan','Female','2000-06-26',29,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Jamil','Pickles','Non-binary','2000-10-22',30,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Wilden','Daen','Male','2000-08-08',31,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Margareta','Vassbender','Female','2000-12-20',32,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Gardie','Rapier','Non-binary','2000-08-26',33,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Riva','Krystof','Male','2001-01-07',34,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Averell','Hillin','Male','2000-12-02',35,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Kiersten','Preddy','Female','2001-05-20',36,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Elisabetta','Maplethorpe','Female','2001-05-09',37,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Jehu','Wiggam','Non-binary','2000-12-18',38,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Gram','Sherlock','Male','2001-01-16',39,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Eachelle','Leetham','Female','2000-11-03',40,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Kennith','Malter','Male','2000-08-24',41,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Tammi','Cattellion','Female','2001-03-09',42,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Alfie','Poyntz','Female','2000-08-11',43,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Goldi','Bruinemann','Female','2000-05-30',44,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Kendell','Lilbourne','Male','2000-10-18',45,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Gisele','Fredy','Male','2000-10-05',46,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (102,'Odie','Medley','Female','2001-05-18',47,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Xaviera','Christol','Female','2001-05-17',48,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Missy','Ianitti','Male','2000-06-01',49,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Alric','Jacquot','Female','2001-04-11',50,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Flori','Lord','Male','2000-11-20',51,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Dillon','Boxhall','Male','2000-06-09',52,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Lorain','Kevis','Non-binary','2001-03-15',53,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Cherish','Lineen','Male','2001-02-09',54,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Sigismund','Sheddan','Male','2000-07-07',55,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Enriqueta','Caird','Female','2001-05-25',56,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Francoise','Sysland','Male','2000-09-03',58,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Adelina','Deinert','Male','2001-02-02',59,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Corrinne','Geraudel','Non-binary','2000-09-23',60,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Hasheem','Tanfield','Non-binary','2000-07-03',61,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Lotte','Sunock','Male','2000-09-15',62,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Kent','Cheesworth','Non-binary','2001-01-03',63,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Kienan','Freeborne','Male','2000-05-27',64,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Trent','Cockill','Male','2000-06-12',65,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Granny','Parrot','Male','2000-08-06',66,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Goddard','Cliss','Male','2000-07-17',67,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Jeramey','Double','Female','2000-11-10',68,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Lib','Fawlkes','Male','2000-08-12',69,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Tiffy','Lymer','Female','2000-06-28',70,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Amalia','Pendry','Male','2001-02-18',71,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Lesly','Ellyatt','Female','2000-10-06',72,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Isidor','Blackstock','Female','2000-06-16',73,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Lenee','Bendix','Female','2000-09-21',74,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Meris','Ironside','Female','2001-03-19',75,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (103,'Cindra','Leader','Male','2001-05-17',76,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (104,'Jewel','Cudbertson','Non-binary','2000-07-04',77,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (104,'Zandra','Tomsu','Male','2000-08-31',78,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (104,'Erma','Sanderson','Female','2000-12-03',79,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (104,'Renie','Rivard','Male','2000-11-01',80,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (104,'Mariquilla','Janusz','Female','2000-08-23',81,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (104,'Ivan','Ferronier','Male','2000-06-12',82,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (104,'Andria','Loughton','Male','2001-05-03',83,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (104,'Evangeline','Belch','Male','2000-08-19',84,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (104,'Gussi','Manske','Female','2000-08-18',85,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (104,'Katerine','Mathivon','Female','2000-08-04',86,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (104,'Benni','Banes','Female','2001-05-15',87,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (104,'Hattie','Pride','Male','2000-11-29',88,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (104,'Ernesto','D''Andrea','Male','2001-04-02',89,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (104,'Freddy','Ternouth','Male','2000-06-24',90,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (104,'Orelie','Conroy','Male','2001-02-17',91,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (104,'Violet','Crumbie','Female','2001-01-05',92,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (104,'Barbe','Mattessen','Non-binary','2001-03-31',93,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (104,'Pamelina','Askin','Female','2001-02-03',94,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (104,'Juliana','Allison','Female','2000-08-15',95,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (104,'Marice','Allen','Female','2001-01-10',96,1);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (104,'Augustine','Fieller','Female','2000-05-26',97,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (104,'Ross','Pearmain','Non-binary','2001-03-11',98,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (104,'Chic','Farman','Non-binary','2000-06-20',99,0);
INSERT INTO VISITOR(V_park_id,fname,lname,gender,dob,Visitor_num,Annual_pass_holder) VALUES (104,'Haven','Godman','Male','2001-05-14',100,0);
